### ISSUE TITLE
Deployment fails when adding - "-Dplay.http.context=/kmanager" to ui.extraArgs in values.yaml

### ISSUE THREAD

**Issue by Schurki** [eshepelyuk/cmak-operator#34]
Hi,

I want to make Kafka manager vailable at <host>/kmanager/. 
There for I have added - "-Dplay.http.context=/kmanager" to the values.yaml.

camp-setup is repeatingly failing with:
`2021-04-28 09:40:33,005 Connecting to cmak.cmak-ns(10.105.231.20):2181, use_ssl: False
2021-04-28 09:40:43,016 Connection dropped: socket connection error: None
2021-04-28 09:40:43,101 Connecting to cmak.cmak-ns(10.105.231.20):2181, use_ssl: False
2021-04-28 09:40:53,112 Connection dropped: socket connection error: None
2021-04-28 09:40:53,213 Failed connecting to Zookeeper within the connection retry policy.
2021-04-28 09:40:53,213 Zookeeper session closed, state: CLOSED
Traceback (most recent call last):
File "/app/bin/cmak2zk.py", line 63, in <module>
cmak2zk()
File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
return self.main(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
return callback(*args, **kwargs)
File "/app/bin/cmak2zk.py", line 39, in cmak2zk
zk.start()
File "/usr/local/lib/python3.8/site-packages/kazoo/client.py", line 635, in start
raise self.handler.timeout_exception("Connection time-out")
kazoo.handlers.threading.KazooTimeoutError: Connection time-out`

logs from zk and ui container in camp pod looks fine, but for ui pod, the health check is failing with:
Liveness probe failed: HTTP probe failed with statuscode: 404

**Comment by eshepelyuk** [comment]
Please send exact values you are using and the logs from `ui` container .

**Comment by eshepelyuk** [comment]
@Schurki and this is not really helpful at all :(
> camp-setup is repeatingly failing 

what is camp-camp setup ?

**Comment by eshepelyuk** [comment]
Hello @Schurki 

Despite the cryptic and ambigous description, I've been able to address and fix the issue.
Check out release [1.6.1](https://github.com/eshepelyuk/cmak-operator/releases/tag/1.6.1)

**Comment by Schurki** [comment]
Hi @eshepelyuk 

i had a busy day and was not able to answer quickly. Also sorry for starting this with just some blurry infos. I just wanted to start a conversation to learn what information might be helpful for sorting this out.

'camp-setup' should be cmak-setup but my autocorrection has tricked me. 

I gave your version 1.6.1  a try, and the pod is coming up properly and the Jobs can also complete successfully. Thanks for that!

Just one thing: while configuring - "-Dplay.http.context=/kmanager" you should avoid a trailing '/' otherwise the /api/health is not accessible

**Comment by eshepelyuk** [comment]
Hi @Schurki 
Yes, you're right about trailing slash.  I will try to figure out some way to prevent users from doing such things.

Thnx for bug report and quick feedback !
