### ISSUE TITLE
Issue activating LDAP

### ISSUE THREAD

**Issue by guisesterheim** [eshepelyuk/cmak-operator#62]
Hi CMAK team!

I'm implementing this operator right now and I'm having issues on activating LDAP. Here is the chart I'm using to configure that.

```
# various settings for CMAK UI container and CMAK application
ui:
  port: 9000
  # additional command line arguments
  extraArgs:
    - "-DbasicAuthentication.enabled=true"
    - "-DbasicAuthentication.ldap.enabled=true"
    - "-DbasicAuthentication.ldap.server=corpdsuat.company.com"
    - "-DbasicAuthentication.ldap.port=389"
    - "-DbasicAuthentication.ldap.username=uid=$capturedLogin$,ou=people,o=company.com,o=email"
    - "-DbasicAuthentication.ldap.password='$capturedPassword'"
    - "-DbasicAuthentication.ldap.search-base-dn=ou=people,o=company.com,o=email"
    - "-DbasicAuthentication.ldap.connection-pool-size=10"
    - "-DbasicAuthentication.ldap.ssl=false"
    - "-DbasicAuthentication.ldap.ssl-trust-all=true"
    - "-DbasicAuthentication.ldap.starttls=false"
```

With this code, when I get to the URL, it prompts me for user and password. Once I enter them I get the "Oops, an error occurred" and on the pod logs I get:

```
! @8243ilg5n - Internal server error, for (GET) [/] ->
 
play.api.UnexpectedException: Unexpected exception[LDAPBindException: invalid credentials]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:247)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:178)
	at play.core.server.AkkaHttpServer$$anonfun$1.applyOrElse(AkkaHttpServer.scala:382)
	at play.core.server.AkkaHttpServer$$anonfun$1.applyOrElse(AkkaHttpServer.scala:380)
	at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:417)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
Caused by: com.unboundid.ldap.sdk.LDAPBindException: invalid credentials
	at com.unboundid.ldap.sdk.LDAPConnection.bind(LDAPConnection.java:2273)
	at com.unboundid.ldap.sdk.LDAPConnection.<init>(LDAPConnection.java:670)
	at com.unboundid.ldap.sdk.LDAPConnection.<init>(LDAPConnection.java:563)
	at controllers.LDAPAuthenticator.ldapConnectionPool$lzycompute(BasicAuthenticationFilter.scala:156)
	at controllers.LDAPAuthenticator.ldapConnectionPool(BasicAuthenticationFilter.scala:144)
	at controllers.LDAPAuthenticator.isAuthorized(BasicAuthenticationFilter.scala:195)
	at controllers.LDAPAuthenticator.checkAuthentication(BasicAuthenticationFilter.scala:169)
	at controllers.BasicAuthenticationFilter.apply(BasicAuthenticationFilter.scala:30)
	at play.api.mvc.Filter$$anon$2.apply(Filters.scala:63)
	at play.api.mvc.Filter$$anon$2.apply(Filters.scala:50)
2023-06-28 13:47:30,569 - [ERROR] application - 
```

The credentials are not invalid. I have just changed and tested it on another application that uses the same LDAP server. That one is working fine. 

Is there anything I have to change on the username and password configuration for the chart?

Thank you very much!

**Comment by eshepelyuk** [comment]
Hello

Unfortunately I cant help om this issue - I have no experience with LDAP, no LDAP servers available and no time to investigate this particular issue.

I can suggest to try to connect to test LDAP server as suggested by CMAK docs and check the results, maybe you can identify smth useful.

**Comment by guisesterheim** [comment]
Hi Ievgenii! Thank you for your feedback. Alright, if this ever comes back to your attention and I can help with any additional info or simulating the scenario, please let me know

**Comment by eshepelyuk** [comment]
> Hi Ievgenii! Thank you for your feedback. Alright, if this ever comes back to your attention and I can help with any additional info or simulating the scenario, please let me know

thnx, 
you are always welcome to investigate and provide PR with possible fixes.
